version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pilates_db
      POSTGRES_USER: pilates
      POSTGRES_PASSWORD: pilates123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: pilates
      RABBITMQ_DEFAULT_PASS: pilates123

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'

  api:
    build: ./backend
    command: sh -c "npm run migration:run:prod && node dist/main"
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://pilates:pilates123@postgres:5432/pilates_db
      RABBITMQ_URL: amqp://pilates:pilates123@rabbitmq:5672
      QUEUES_ENABLED: 'true'
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: pilatesos-api
      KAFKA_NOTIFICATIONS_GROUP_ID: pilatesos-notifications
      JWT_SECRET: super-secret-key
      JWT_REFRESH_SECRET: refresh-secret-key
      ADMIN_NAME: Administrador
      ADMIN_EMAIL: admin@pilatesos.com
      ADMIN_PASSWORD: admin123
      DB_SYNC: 'false'
      PORT: 3000
    depends_on:
      - postgres
      - rabbitmq
      - kafka

  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - api

volumes:
  pgdata:
