version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pilates_db
      POSTGRES_USER: pilates
      POSTGRES_PASSWORD: pilates123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: pilates
      RABBITMQ_DEFAULT_PASS: pilates123

  api:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://pilates:pilates123@postgres:5432/pilates_db
      RABBITMQ_URL: amqp://pilates:pilates123@rabbitmq:5672
      JWT_SECRET: super-secret-key
      JWT_REFRESH_SECRET: refresh-secret-key
      DB_SYNC: 'true'
      PORT: 3000
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - api

volumes:
  pgdata:
